cargo2nix/cargo2nix

default.nix
nixpkgs.nix
overlay/json2toml.nix
overlay/mkcrate.nix
overlay/real-host-triple.nix
overlay/toml2json.nix

This is needed for cross compiling to `musl` on macOS.

Fix cross compilation on macOS

---

Cargo.lock
Cargo.nix
Cargo.toml
default.nix
overlay/lib/default.nix
overlay/lib/profiles.nix
overlay/mkcrate.nix
src/main.rs
src/manifest.rs

This PR adds support for the [`[profile.*]`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections) sections defined at the top level `Cargo.toml`.

Propagate profiles

---

default.nix
overlay/default.nix
overlay/make-package-set/full.nix
overlay/mkcrate-nobuild.nix
overlay/overrides.nix
shell.nix

This PR allows overrides to propagate environment variables further up the dependency graph, which reduces the work to create a development shell.
CC @edude03 @antigravityla.
Resolves #33 
Resolves #34

Propagate environment variables to root crates

---

overlay/make-package-set/full.nix

* Add top-level `tests` directory to `localPatterns` in `overlay/mkcrate.nix`.
As described in #40, `cargo2nix` currently does not output integration tests by default when building the crate in test mode. This is because `localPatterns` does not include the top-level `tests` directory in the default path regex. This directory is standard for any Cargo project, and the current behavior of not including integration tests when `compileMode = "test"` is quite surprising, especially for a new user. I believe it should be fine to include this directory by default, if it exists.
Fixes #40.

Include integration test binaries in test mode

---

README.md

* Document broken `fromTOML` builtin as a common issue in `README.md`.
It seems that Nix 2.1.3 provides a bugged version of `builtins.fromTOML` which chokes when parsing `Cargo.toml` manifests that have `cfg(...)` keys in them, as shown below:
```toml
[target.'cfg(target_os = "linux")'.dependencies.rscam]
```
Removing the whitespace around the equal sign resolves the issue for now, but ultimately, the best thing to do is to upgrade to a newer version of Nix. I can confirm on my work machine that Nix 2.3.1 does not have this issue. If we can find out what precise version of Nix fixed this bug, we should probably update the `README.md` text at a later date.

Document broken builtins.fromTOML in Nix 2.1.3

---

Cargo.nix
default.nix
src/main.rs

Becase `unknown.<crate>.<version>` is just too mouthful.

Generate a set of all workspace crates

---

overlay/overrides.nix

There's a less hacky way to disable `systemd`.

Fix postgresql patch

---

.gitattributes

This will make language stat of the repo more sensible.

Exclude generated Cargo.nix from the repo language stat

---

overlay/mkcrate.nix
overlay/utils.sh

During the work on Cumbertrade I've noticed that `cargo` is producing a lot of noise during a build of `cargo2nix`-ed packages. Related issue is here: https://github.com/tenx-tech/engineering-program/issues/721
This PR won't just remove the `-vvv` flag from `cargo` invocation in `mkRustCrate`, but will make the verbosity level configurable since I believe that this high verbosity was added for a reason and still might be useful in some cases.
cc @workflow @ebkalderon

Less verbose cargo

---

overlay/overrides.nix

`Security` is actually a [direct build input](https://github.com/briansmith/ring/blob/4c392ad338f61ea166a29c83d4208e8edfecc6ca/src/rand.rs#L405) for `ring`, not `webpki-roots`. `webpki-roots` indirectly depends on `ring` and happens to include a [binary](https://github.com/ctz/webpki-roots/blob/master/src/bin/process_cert.rs), which sets off the linking error. 
As a side note, we should always apply overrides to the "deepest" crate in the dependency tree. This benefits more crates and reduces the number of overrides needed.
CC @port3000.

Add override for ring instead of webpki-roots

---

overlay/mkcrate.nix

* Fix building `[lib]` targets with non-standard names.
Currently, `cargo2nix` assumes that all crate library targets follow the format of `lib<crate_name_with_underscores>.rlib`, which isn't always true. It turns out that the library target of the [`sha-1`] crate uses a non-standard rlib name which doesn't match the name of the crate, thanks to the `lib.name` attribute in the `Cargo.toml`. Because of this, the `sha-1` crate doesn't build correctly in `cargo2nix`.
[`sha-1`]: https://github.com/RustCrypto/hashes/tree/master/sha1
This commit fixes the build by first checking whether the `lib.name` attribute exists in the crate's `Cargo.toml` first, and if it doesn't exist, it will fall back to `crateName`.
CC @port3000

Fix building lib targets with non-standard names

---

Cargo.lock
Cargo.nix
Cargo.toml
LICENSE

* Bump crate version to 0.7.0 and regenerate `Cargo.nix`.
We have had many significant updates to `cargo2nix` recently, and I believe this warrants tagging a brand-new release.

Prepare release 0.7.0

---

overlay/overrides.nix

* Add macOS package override for `fsevent-sys` linking against `CoreServices`.
This commit should allow `fsevent-sys`, and in turn [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer), to successfully build under macOS with `cargo2nix`. See the commit message description for why I chose to do this.
In case you're curious, the steps for building `rust-analyzer` on macOS Mojave are as follows:
1. `git clone https://github.com/rust-analyzer/rust-analyzer` 
2. Create a minimal `default.nix` based on the one in this repository, targeting the `ra_lsp_server` crate specifically.
3. Change the Rust version to `1.40.0`.
4. Run `cargo2nix -f` at the `rust-analyzer` repo root.
5. Run `nix-env -if default.nix -A package --arg crossSystem null`.
6. You now have `ra_lsp_server` available in …

Add macOS package override for fsevent-sys

---

overlay/overrides.nix

The [`pkg-config`](https://crates.io/crates/pkg-config) crate cannot cross-compile packages unless the `PKG_CONFIG_ALLOW_CROSS` environment variable is set, throwing the [`CrossCompilation`] error otherwise.
[`CrossCompilation`]: https://docs.rs/pkg-config/0.3.17/pkg_config/enum.Error.html#variant.CrossCompilation
This commit automatically sets `PKG_CONFIG_ALLOW_CROSS=1` as a propagated environment variable for any dependency tree which depends on `pkg-config` if the `stdenv` host platform and build platform differ.
This should fix cross-compilation of certain crates which rely on `pkg-config`, such as [`curl-sys`](https://crates.io/crates/curl-sys).

Set PKG_CONFIG_ALLOW_CROSS if host and build platforms differ

---

src/template.rs

* Add missing `url` field to `Source::Git` enum variant.
This fixes a regression introduced by #80 which results in a templating failure for Git crate dependencies. I noticed it after running `cargo2nix -f` against the latest commit of `rust-analyzer`.
Since `cargo2nix` 0.8.1 hasn't been officially released yet, this requires no version number increase.

Fix codegen regression for Git dependencies

---

src/main.rs

* Simplify `resolve_ws_with_opts()` invocations in several methods by using `ResolveOpts::everything()` and `ResolveOpts::new()` to reduce boilerplate.
* Remove explicit return in `all_eq()`.
* Remove explicit lifetimes from `all_features()`.
* Add single trailing newline for readability.
* Keep data structures close to their `impl` blocks.

Clean up some workspace resolution code

---

.circleci/config.yml

* Switch to new `cargo2nix` cache in CircleCI. This change is coupled with the addition of `CACHIX_SIGNING_KEY` to the build-time secrets.
* Push `nix-build` output inside CI build step, using [this configuration](https://github.com/tweag/clodl/blob/master/.circleci/config.yml) as reference.
Should hopefully fix CI for #89.

Switch to new Cachix in CI

---

README.md
default.nix

* Specify `crossSystem ? null` for the `cargo2nix` Rust crate.
Since the `cargo2nix` crate cannot even compile under `musl` on Linux anyway, thanks to the `nix-prefetch-git` dependency added in #62, it no longer makes sense to recommend cross-compiling to that platform by default. Instead, we should default to compiling for the system and `libc` of the build platform, where the command is likely to be running anyway.
This is not a breaking change for downstream users of the `cargo2nix` overlay. It also should not affect future installations of the `cargo2nix` CLI tool because the README already recommended installing with `--arg crossSystem null` anyway.
Fixes #88.

Don't cross-compile cargo2nix to musl by default

---

overlay/make-package-set/full.nix
overlay/make-package-set/simplified.nix

* Make `packageOverrides` default to `rustBuilder.overrides.all`.
Follow-up to https://github.com/tenx-tech/cargo2nix/pull/93#pullrequestreview-375921456.

Make packageOverrides default to overrides.all

---

src/main.rs

* Attempt to copy tempfile if atomic rename fails.
This should fix cases where `tempfile::NamedTempFile::persist()` fails due to `Invalid cross-device link (os error 18)`, which is likely due to atomic file moves being problematic on Linux with `/tmp` on `tmpfs` or an otherwise separate filesystem from the root partition.
Would you mind trying this branch and confirm whether it fixes your issue, @vbrandl?
Fixes #97.

Attempt to copy tempfile if atomic rename fails

---

README.md

* Change default lint cap statement in `README.md` to apply to all crates, not just `failure`.

Fix incorrect lint cap statement in README.md

---

examples/1-hello-world/default.nix

* Remove implied `packageOverrides` from `hello-world` project. We leave the commented form in the `bigger-project` example for demonstration purposes.
This value is implied if unspecified by the user, and it should've been removed in #95.

Remove implied packageOverrides from hello-world project

---

overlay/mkcrate.nix
overlay/overrides.nix

* Add `buildPackages.pkg-config` as propagated native build input to `pkg-config` override.
* Remove `pkg-config` native build input for `mkCrate`.
I don't really think it makes sense to have `pkg-config` as a required native build input for `mkCrate` but not any other meta-packaging or meta-compilation tool, for example. Instead, we should add `pkg-config` to the `pkg-config` crate override in `overlay/overrides.nix`. This way, crates that require it will have access to it, while all others that don't will avoid pulling it in unnecessarily.
I've tried rebuilding `cargo2nix` itself (which depends on `pkg-config` for a few dependencies) as well as larger crates such as `rust-analyzer` without any apparent issues. I'd appreciate a second or third pair of eyes to confirm that this change …

Remove pkg-config nativeBuildInput in mkCrate

---

default.nix

Almost anything the user overlays would be intended to fix will require being
the last overlay in the chain.  It's impossible to modify Rust dependencies in
the first overlay position without even more clever hacks to the mozilla or
cargo2nix overlays.
Change developed originally here:
https://github.com/tenx-tech/cargo2nix/commit/885488ed0a2431c19d5dca3c9a015ffb16b0f3ee#diff-5712e736e0de6ba170577f8472c398e9R23

Move user overlays to tail

---

README.md
overlay/lib/fetch.nix
templates/Cargo.nix.tera

* Add notice regarding caveats of `builtins.fetchGit` to `README.md`.
* Switch from `fetchgitPrivate` (which was removed upstream) to `builtins.fetchGit`.
* Ignore the `sha256` argument used in `fetchCrateGit` for backwards compatibility. We should remove this argument from the overlay and codegen completely in a subsequent minor release.
Original commit authored by @macs-overdrv and cherry-picked from #109. CC @Mic92
Fixes #108.

Update to builtins.fetchGit

---

overlay/overrides.nix

* Use `pkgs.pkg-config` over `pkgs.buildPackages.pkg-config`.
* Pass `pkgs.pkg-config` to `propagatedBuildInputs` instead of `propagatedNativeBuildInputs`.
* Always include `pkgs.pkg-config` as a propagated build input in the crate override, regardless of whether we are cross-compiling or not, fixing a bug introduced in #104.

Fix pkg-config override, indirectly fixing curl-sys

---

overlay/overrides.nix

When I use [protoc-rust-grpc](https://crates.io/crates/protoc-rust-grpc) crate which uses [protoc](https://crates.io/crates/protoc) crate internally, I get an error due to `protoc` file not being found.
```
--- stderr
thread 'main' panicked at 'protoc version: Custom { kind: NotFound, error: "failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)" }', src/lib.rs:97:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This override for [protoc](https://crates.io/crates/protoc) crate seems to help with that.

Add protobuf to protoc in override

---

Cargo.lock
Cargo.nix
Cargo.toml
README.md

* Bump `cargo2nix` crate version to 0.8.3 and regenerate `Cargo.nix`.
* Update outdated example in `README.md`.
Since this version of the `Cargo.nix` format is backwards-compatible with the current release, and all manner of changes merged since then have been either forward-compatible bugfixes or minor additions to the overlay, I believe a patch release of 0.8.3 is sufficient here. I'll prepare a new GitHub release changelog immediately after this gets merged.
CC @edude03

Prepare release 0.8.3

---

Cargo.nix
default.nix
overlay/make-package-set/full.nix
overlay/mkcrate.nix
src/platform.rs
templates/Cargo.nix.tera

Howdy!
We're using cargo2nix, but ran into a snag. Our particular project makes use of AES via the "aes" crate. That particular crate uses conditions based on target-feature to decide whether to pull in a hardware-optimized crate, or use a software implementation instead:
```
[target.'cfg(not(all(target_feature="aes", target_feature = "sse2", any(target_arch = "x86_64", target_arch = "x86"))))'.dependencies]
aes-soft = { version = "0.4", path = "aes-soft" }
```
Today, cargo2nix doesn't support that.
I've created this PR to invite discussion about how that should be supported. For now, I've implemented a simple solution, but it isn't without drawbacks. The main one being that it is a breaking change currently, if this PR were adopted, folks using it would need to regenerate their Cargo.nix …

Support for specifying target-feature and target-cpu for a package set

---

src/template.rs

* Escape TOML output in `profilesByName` using a combination of `str::{escape_debug,replace}`.
The Tera templating code for `profilesByName` hadn't been rigorously tested, and as such, it didn't perform proper escaping of sensitive characters (e.g. `${`, `"`, and so on) before embedding the unsanitized TOML into a double-quoted Nix string in the `Cargo.nix`. This string might also contain newlines or other control characters which would need to be escaped as well.
This commit utilizes `String::escape_debug()` to perform the bulk of the escaping work, sanitizing common control characters such as `\n`, `\r`, and `\t`, and then we also replace all instances of `${` with `\${` to avoid accidental string interpolation of variables.
This bug was first introduced in #80, when we first ported …

Escape embedded TOML in profilesByName properly

---

overlay/mkcrate-nobuild.nix

* Add missing arguments to `mkcrate-nobuild.nix`, fixing an unforseen bug in #119.
Our existing `nix-shell` integration broke because the `hostPlatformCpu` and `hostPlatformFeatures` function arguments were missing from `overlay/mkcrate-nobuild.nix`. This commit adds those missing arguments back in so we can restore the broken functionality.

Fix broken nix-shell integration

---

Cargo.lock
Cargo.nix
Cargo.toml
default.nix
src/main.rs
src/template.rs
templates/Cargo.nix.tera

* Simplify `checksum` field of `ResolvedPackage` from `Option<Cow<'a, str>` to `Option<&'a str>`.
* Remove unused `sha256` argument for Git dependencies.
* Remove `serde_json` dependency.
* Remove private `prefetch_git` function.
* Remove `nix-prefetch-git` wrapper from `default.nix`.
This argument has been rendered unused since the transition to `builtins.fetchGit` for all Git dependencies was made (#113). Since a minor release is coming soon, due to #119, this breaking change should now be safe to roll out.
Closes #102.

Remove unused sha256 argument for Git dependencies

---

overlay/mkcrate.nix

As the title says. This has apparently been around for a long time.

Fix indentation in overlay/mkcrate.nix

---

examples/1-hello-world/README.md
examples/2-bigger-project/README.md

* Update READMEs of example projects to reference `v0.8.3` instead of outdated versions. This text should have been updated back when 0.8.3 was released, but it seems it slipped through.

Update outdated Git tag in example project READMEs

---

.circleci/config.yml

* Invoke `nix-shell` in CI to verify the validity of `shell.nix` and `overlay/mkcrate-nobuild.nix`.
We've been bitten by this before (#123), so I think this change would come in handy.

Validate shell.nix and mkcrate-nobuild.nix in CI

---

overlay/mkcrate.nix
overlay/utils.sh

* Switch to the `target/${triple}/release` or `target/${triple}/debug` directory when installing a crate, now properly respecting the `release` boolean flag.
Note that this fix should be rendered unnecessary by #118, but we still need to support older versions of Rust <1.41.0.

Fix install_crate behavior for debug builds

---

default.nix
overlay/mkcrate.nix
overlay/utils.sh

* Use `--message-format=json` to install artifacts on Rust >=1.41.0, falling back to the older method for compatibility with older versions of Rust that lack `out_dir` in the JSON output (https://github.com/rust-lang/cargo/pull/7622).
* Build examples in CI using the `HEAD` version of the overlay instead of the pinned versions, to actually check whether the current PR broke something.
* Address some `shellcheck` lints and clean up formatting of `overlay/utils.sh`.
* Lightly reorganize expression in `overlay/mkcrate.nix`.
This should hopefully fix the observed issues with recent versions (1.4X) of Rust placing test binaries in `target/deps` instead of `target`, thereby breaking the `install_crate` Bash function and the `cargo2nix` test runner.
@edude03 and @antigravityla, please confirm if …

Use --message-format=json to install artifacts

---

overlay/lib/fetch.nix

* Remove leftover `sha256` argument from `fetchCrateGit`.
This argument was recently removed from the codegen side in #124, but unfortunately, the corresponding change to the Nix overlay were forgotten.
Fixes #132.

Fix fetcher for Git dependencies

---

overlay/utils.sh

* Rename `$out/build_output` directory to `$out/build_script_output` for clarity, remove TODO comment.
When PR #118 was merged, the final name for the directory containing the build script output wasn't finalized. We've settled on calling it `build_script_output` for the sake of clarity.

Eliminate TODO about build script output dir

---

examples/3-static-resources/README.md

* Correct typo "eand" -> "and".
* Remove noisy `result` line from filtering table.
Follow-up to #135 which addresses feedback given by @antigravityla on that PR.

Follow-up fixes for static resources project tutorial

---

default.nix
examples/1-hello-world/default.nix
examples/2-bigger-project/default.nix
examples/3-static-resources/default.nix

* Upgrade `nixpkgs-mozilla` version pins to `18cd4300e9bf61c7b8b372f07af827f6ddc835bb`.
This includes an upstream fix for the missing `libz.so.1` error seen with Rust 1.46.0 (https://github.com/mozilla/nixpkgs-mozilla/commit/ab9b53ebbbf9fe803e0fd7718192e7f3ba2c7759). It should resolve the issue previously preventing CircleCI from passing in PR #141.

Upgrade nixpkgs-mozilla pins to fix CI with Rust 1.46

---

examples/1-hello-world/default.nix
examples/2-bigger-project/default.nix
examples/3-static-resources/default.nix

This should hopefully unblock CI for us until we can upgrade to a newer verison of Cargo which supports Lockfile format V2.
We can revert this once #145 is resolved.

Temporarily pin examples to Rust 1.46.0

---

overlay/overrides.nix

Two simple overrides and one drive-by override fixup.
Use of `$RUSTC` will fail if we ever switch how it's provided to the build env.  Recommend a followup PR to always provide `rustc` on the `$PATH` for other creative build.rs scripts which attempt to invoke it directly

Udev and dbus overrides

---

LICENSE

* Update `LICENSE` to credit the individual `cargo2nix` developers as copyright holders.

Update copyright holders to indicate ownership transfer

---

CONTRIBUTING.md
README.md
examples/1-hello-world/README.md
examples/1-hello-world/default.nix
examples/2-bigger-project/README.md
examples/2-bigger-project/default.nix
examples/3-static-resources/README.md
examples/3-static-resources/default.nix

* Update all older GitHub URLs containing `tenx-tech` to point to this our new GitHub organization.
* Fix CircleCI status badge because `tenx-tech` no longer controls this repository.

Update URLs to point to cargo2nix GitHub organization

---

default.nix
examples/2-bigger-project/default.nix
overlay/make-package-set/full.nix
overlay/make-package-set/simplified.nix

When a package is built by flakes which require reproducible inputs including downloads via `fetchUrl` cargo2nix fails to build mozilla rust-overlay.
This PR introduces an option rustCrateSha256 which is being passed to rust-overlay to fix the problem mentioned above.

rustCrateSha256 for compatibility with flakes

---

README.md
overlay/lib/fetch.nix
overlay/mkcrate.nix
overlay/overrides.nix

These were breaking the version of remarshal in use
Fixes #149 
Fixes #172
Fixes #167
Getting this into CI while I figure out what was broken.  All output from jq would have contained these nulls and it should have been breaking more

strip nulls from the outputs of the first jq pipe

---

examples/4-independent-packaging/Cargo.nix
examples/4-independent-packaging/default.nix
templates/Cargo.nix.tera

Fixes #169
`localPatterns` is used whenever the source is local (not for `fetchGit` etc).  When concatenating crate paths in generated `Cargo.nix`, the `fetchCrateLocal` call filtered each workspace crate to nothing, causing nix to error when it couldn't "unpack the archive" and requiring working around by setting `localPatterns` to include each workspace crate.
The application point for `localPatterns`
https://github.com/cargo2nix/cargo2nix/blob/master/overlay/make-package-set/full.nix#L53-L55
Tested by converting a `fetchGit` to relative path for Rust-Analyzer in 4th example.  Reproduced and fixed issue.  Cargo2nix and other examples don't do this path concatenation and were unaffected.  Git sources are unaffected.

Fix workspace crate paths

---

overlay/mkcrate-nobuild.nix
overlay/mkcrate.nix

Benchmarks were missing `dev-dependencies`

Fix missing benchmark dependencies

---

overlay/overrides.nix

`openssl-sys` expects a rust triple and not a nix triple.
The build break when the rust and the nix triple are different, for example on armv6.
It is the same kind of bugs as the one I fixed on #201.
This patch has been tested on our project where we use cargo2nix, openssl & cross compile to armv6:
- this is what a failed build looks like, before the patch: [#1391](https://drone.deuxfleurs.fr/Deuxfleurs/garage/1391/5/3)
- this is what a working build looks like, after the patch: [#1408](https://drone.deuxfleurs.fr/Deuxfleurs/garage/1408/5/3)

openssl-sys expects a rust triple

---

overlay/make-package-set/user-facing.nix

Resolves an issue where `makePackageSetInternal` is called with an unexpected argument when `extraRustComponents` is set.

Remove extraRustComponents from extraArgs

---

overlay/mkcrate-utils.sh
overlay/mkcrate.nix

Currently cargo2nix does not build any project which uses diesel. The method used to locate crates within a multi-crate workspace matches multiple crates. In this particular case, [grep](https://github.com/cargo2nix/cargo2nix/blob/5127b95a61bbf211f975ea9faf2fb31251a4a413/overlay/mkcrate.nix#L162) matches the crates diesel and diesel_cli. Therefore, the following `cd` command fails, since two paths are specified.
Instead of using a grep, use cargo metadata and parse the output with jq.

use a more robust method to find crates in multi-crate workspaces

---

overlay/mkcrate.nix

This is more consistent with the [nixpkgs manual][0]. Code adapted from [here in nixpkgs][1].
[0]: https://nixos.org/manual/nixpkgs/stable/#ssec-install-phase
[1]: https://github.com/NixOS/nixpkgs/blob/d8916eaeaf7080aa0642122d34d04f683ccf1f17/pkgs/stdenv/generic/setup.sh#L1134-L1155
Not sure if there are tests somewhere I need to update in this repository, though I did [test with my own code](https://or.computer.surgery/charles/cargo-shim/-/commit/1b4051ca1d698fcdd43fda674b500d01e3f43b63) that I originally wanted this feature for; you can try it yourself with `nix run 'git+https://or.computer.surgery/charles/cargo-shim?ref=cargo2nix-install-hooks'` (it just prints a help message then exits). You can tell it works because if it didn't, the rename would never happen and thus `nix run` would …

Run pre/post install hooks by default

---

overlay/overrides.nix

I came across another exception: `sqlx-macros` that require `SystemConfiguration.framework` on OSX.

use sqlx-macros overries for osx: SystemConfiguration

---

overlay/mkcrate.nix

Something is likely wrong if `$manifest_path` is empty, but at least it won't trigger an unhelpful syntax error in bash.

Quote `$manifest_path` so it doesn't break comparison if empty

---

templates/Cargo.nix.tera

The special URL syntax is deprecated:
https://github.com/NixOS/rfcs/blob/master/rfcs/0045-deprecate-url-syntax.md

Quote `url` value in `fetchCrateGit` output

---

overlay/mkcrate.nix

This became necessary starting with Rust nightly 2024-03-26. But it has never been a good idea to access network in Nix builds.
Both `--offline` and `net.offline` appeared in Rust 1.36.
https://github.com/rust-lang/cargo/pull/6934

Configure cargo to avoid any network access

---

examples/4-independent-packaging/Cargo.nix
examples/4-independent-packaging/README.md
examples/4-independent-packaging/flake.lock
examples/4-independent-packaging/flake.nix

Newer versions of rust-analyzer are not supported without #362 (Refactor of toml munging) that is not stable yet.
Use tag for rust-analyzer in `flake.nix`. Update tag in `README.md`.

examples: Revert rust-analyzer to version 2022-09-12

---

overlay/overrides.nix

This was forgotten in 546b5b0e7406662d65cc0da9eefb2b0067c379a1.

Add override libsqlite3-sys to all

---

examples/4-independent-packaging/Cargo.nix
examples/4-independent-packaging/flake.lock
overlay/mkcrate-utils.sh
overlay/mkcrate.nix
src/main.rs
templates/Cargo.nix.tera

This applies the changes from #333 to the `main` branch.
On the topic of branches, the readme says that users should follow `unstable` to get the latest changes. But for a while people have been merging to `main` instead. Maybe because `unstable` has branch protections enabled, or maybe because people are used to using `main`.
Should we fast-forward `unstable` to `main`, and stop using `main`, or should we update the documentation to tell people to follow `main` instead of `unstable`?

Support Workspace Metadata

---

Cargo.nix
examples/1-hello-world/Cargo.nix
examples/2-bigger-project/Cargo.nix
examples/3-cross-compiling/Cargo.nix
examples/4-independent-packaging/Cargo.nix
overlay/make-package-set/internal.nix
overlay/make-package-set/user-facing.nix
overlay/mkcrate-nobuild.nix
overlay/mkcrate.nix
templates/Cargo.nix.tera

This change automatically applies the `.cargo/config.toml` settings found in the repository root. to accomplish this I have rewritten the config.toml generation logic to use the nix toml generators, instead of generating it inline.
Fixes #181.

Respect config.toml

---

README.md

i was frustrated that i had to look through the code to see how to use newer rust versions to find out that i just needed to update the rust-overlay version through my flake so i added the steps to do that in the readme if thats ok
as per #379 and #181 it seems that currently only versions up until verison 1.78 work so maybe i should add that disclaimer as well?

add note about using newer rust versions in readme

---

overlay/mkcrate-utils.sh

The Cargo.toml munging code did not correctly disect packages where there is a root packages and several sub-packages.
Now all package-related Cargo.toml options are removed from workspace manifests and all workspace-related Cargo.toml options are removed from package manifests
This fixes #392.
@halletj, after we merge this we should cut a 0.12.0. users are getting confused about why the current release version is broken

Add support for workspaces with root package
