.direnvrc, .envrc, .gitignore, shell.nix
Adds a working `direnv` config for hacking on cargo2nix itself
=> Replace broken .envrc with a working shell

.envrc, default.nix
* Watch default.nix for changes
* Woraround cert-issues in direnv/lorri
cc: @dingxiangfei2009 @trha @antigravityla
=> Direnv improvements

default.nix
cc: @dingxiangfei2009 @antigravityla @trha
=> Document naming convention for the config format

.circleci/config.yml, default.nix, overlay/default.nix, overlay/run-tests.nix
This function runs all tests for a crate inside Nix.
=> Add runTests

overlay/run-tests.nix
😔 An oversight from the previous PR.
=> Fix runTests not accepting additional parameters

Cargo.nix, src/main.rs
I think it cannot be made any more smaller.. now!
=> Make the codegen more succinct

overlay/overrides.nix
* Disable `patchOpenssl` override so `openssl` compiles on newer Nixpkgs.
It seems that newer versions of Nixpkgs have `openssl` default to OpenSSL 1.1.1, which fails to cross-compile on all platforms except for `x86_64-linux` to `lib.systems.examples.musl64`. To avoid breakage by users relying on newer Nixpkgs versions and aren't cross-compiling, we turn off our OpenSSL patch overrides if the host and build platforms match.
Fixes #96.
=> Disable OpenSSL patches if not cross-compiling

overlay/overrides.nix
Closes https://github.com/tenx-tech/cargo2nix/issues/140
=> Add zmq-sys override

examples/1-hello-world/default.nix, examples/2-bigger-project/default.nix, examples/3-static-resources/default.nix
=> pin examples to 0.9.0 hash

overlay/overrides.nix
Needed this for building a crate (rusqlite), so I added it.
=> Add override for libsqlite3-sys

src/platform.rs
Currently, there is a bug with cargo2nix in the way it interprets `target_arch` conditionals.
`target_arch` values are (partially) defined [in the doc](https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch) as the following set:  x86 x86_64 mips powerpc powerpc64 arm aarch64.
This set does not overlap with how the CPUs are defined by nix in at least two points:
- rust `x86` refers to `i686` in nix
- rust `arm` both refers to v6 (identified as `armv6l`) and v7 (identified as `armv7l`) in nix.
This patch adds a function to map `target_arch` to the correct `cpu`.
This patch has been tried with:
- `ring` - otherwise it fails with `use of undeclared crate or module spin` when compiled with `armv7l-unknown-linux-gnueabihf`
- `sha2` - otherwise it fails with `use of …
=> Translating target_arch to nix cpu is required

examples/1-hello-world/README.md, flake.nix
`nix run github:cargo2nix/cargo2nix -- -f`
Fun times with flakes.
=> Fix default app

.github/workflows/ci.yml, README.md
Show both mac & linux builds last check state on README.
Fixes #210
=> Dynamic ci

flake.nix, overlay/workspace-shell.nix
=> Make shell pass through customizations

overlay/make-package-set/user-facing.nix
=> Wrap cargo2nix binary with rustc on the PATH

README.md, flake.nix
A shell with cargo2nix, rustc, and cargo all in one flake path for `nix develop`   
Progress on
https://github.com/cargo2nix/cargo2nix/issues/254
=> Bootstrap Shell

.envrc, .github/workflows/ci.yml, README.md, examples/1-hello-world/README.md, examples/1-hello-world/flake.lock, examples/1-hello-world/flake.nix, examples/2-bigger-project/README.md, examples/2-bigger-project/flake.nix, examples/3-cross-compiling/README.md, examples/3-cross-compiling/flake.nix, examples/4-independent-packaging/README.md, examples/4-independent-packaging/flake.nix, examples/README.md, flake.lock, flake.nix, overlay/default.nix, overlay/lib/default.nix, overlay/lib/overrides.nix, overlay/lib/profiles.nix, overlay/make-package-set/user-facing.nix, overlay/mkcrate.nix
more nix 2.8 style attributes
use of `inputs: with inputs` style argument plumbing
=> refinining some code

flake.nix
Many files are generated.  When you draft your changes, please separate out
commits that affect:
- Cargo.lock
- Cargo.nix
- flake.lock
Keeping these changes isolated in specific commits makes it much easier to pull
in your changes in parallel with other features.  Maintainers may harvest your
changes.  We only guarantee to preserve authorship in the git log (when we
remember to do so).
1. Fork this repository into the personal GitHub account
2. Select the appropriate branch, release-<version> for stable changes, unstable
for breaking changes
3. Make changes on the personal fork
4. Make a Pull Request against this repository
5. **Allow maintainers to make changes to your pull request** (there's a checkbox)
6. Once the pull request has been approved, you will be thanked and observe your …
=> flake: quote urls

README.md
Fix minor typos in the `README.md`.
=> Fix typos in the `README.md`

overlay/mkcrate-utils.sh
This allows some crates like cxx-qt to build with some extra build overrides.
The new syntax was introduced with rust 1.77: https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key
=> Add support for the new build script crate metadata syntax
